<?php

namespace App\Http\Controllers;

use App\Models\Booth;
use Illuminate\Http\Request;

class FairhallController extends Controller
{
    
    
    // Booth Image
    public function fairhall() {

        
            return view ('fairhall', [
                'booth_1' => Booth::where('booth_number', 'booth_1')->value('company_logo'),
                'booth_2' => Booth::where('booth_number', 'booth_2')->value('company_logo'),
                'booth_3' => Booth::where('booth_number', 'booth_3')->value('company_logo'),
                'booth_4' => Booth::where('booth_number', 'booth_4')->value('company_logo'),
                'booth_5' => Booth::where('booth_number', 'booth_5')->value('company_logo'),
                'booth_6' => Booth::where('booth_number', 'booth_6')->value('company_logo'),
                'booth_7' => Booth::where('booth_number', 'booth_7')->value('company_logo'),
                'booth_8' => Booth::where('booth_number', 'booth_8')->value('company_logo'),
                'booth_9' => Booth::where('booth_number', 'booth_9')->value('company_logo'),
                'booth_10' => Booth::where('booth_number', 'booth_10')->value('company_logo'),
                'booth_11' => Booth::where('booth_number', 'booth_11')->value('company_logo'),
                'booth_12' => Booth::where('booth_number', 'booth_12')->value('company_logo'),
                'booth_13' => Booth::where('booth_number', 'booth_13')->value('company_logo'),
                'booth_14' => Booth::where('booth_number', 'booth_14')->value('company_logo'),
                'booth_15' => Booth::where('booth_number', 'booth_15')->value('company_logo'),
                'booth_16' => Booth::where('booth_number', 'booth_16')->value('company_logo'),
                'booth_17' => Booth::where('booth_number', 'booth_17')->value('company_logo'),
                'booth_18' => Booth::where('booth_number', 'booth_18')->value('company_logo'),
                'booth_19' => Booth::where('booth_number', 'booth_19')->value('company_logo'),
                'booth_20' => Booth::where('booth_number', 'booth_20')->value('company_logo'),
                'booth_21' => Booth::where('booth_number', 'booth_21')->value('company_logo'),
                'booth_22' => Booth::where('booth_number', 'booth_22')->value('company_logo'),
                'booth_23' => Booth::where('booth_number', 'booth_23')->value('company_logo'),
                'booth_24' => Booth::where('booth_number', 'booth_24')->value('company_logo'),
                'booth_25' => Booth::where('booth_number', 'booth_25')->value('company_logo'),
                'booth_26' => Booth::where('booth_number', 'booth_26')->value('company_logo'),
                'booth_27' => Booth::where('booth_number', 'booth_27')->value('company_logo'),
                'booth_28' => Booth::where('booth_number', 'booth_28')->value('company_logo'),
                'booth_29' => Booth::where('booth_number', 'booth_29')->value('company_logo'),
                'booth_30' => Booth::where('booth_number', 'booth_30')->value('company_logo'),
                'booth_31' => Booth::where('booth_number', 'booth_31')->value('company_logo'),
                'booth_32' => Booth::where('booth_number', 'booth_32')->value('company_logo'),


                // ToolTip Logo
                'toolTip_1' => Booth::where('booth_number', 'booth_1')->value('tooltip_logo'),
                'toolTip_2' => Booth::where('booth_number', 'booth_2')->value('tooltip_logo'),
                'toolTip_3' => Booth::where('booth_number', 'booth_3')->value('tooltip_logo'),
                'toolTip_4' => Booth::where('booth_number', 'booth_4')->value('tooltip_logo'),
                'toolTip_5' => Booth::where('booth_number', 'booth_5')->value('tooltip_logo'),
                'toolTip_6' => Booth::where('booth_number', 'booth_6')->value('tooltip_logo'),
                'toolTip_7' => Booth::where('booth_number', 'booth_7')->value('tooltip_logo'),
                'toolTip_8' => Booth::where('booth_number', 'booth_8')->value('tooltip_logo'),
                'toolTip_9' => Booth::where('booth_number', 'booth_9')->value('tooltip_logo'),
                'toolTip_10' => Booth::where('booth_number', 'booth_10')->value('tooltip_logo'),
                'toolTip_11' => Booth::where('booth_number', 'booth_11')->value('tooltip_logo'),
                'toolTip_12' => Booth::where('booth_number', 'booth_12')->value('tooltip_logo'),
                'toolTip_13' => Booth::where('booth_number', 'booth_13')->value('tooltip_logo'),
                'toolTip_14' => Booth::where('booth_number', 'booth_14')->value('tooltip_logo'),
                'toolTip_15' => Booth::where('booth_number', 'booth_15')->value('tooltip_logo'),
                'toolTip_16' => Booth::where('booth_number', 'booth_16')->value('tooltip_logo'),
                'toolTip_17' => Booth::where('booth_number', 'booth_17')->value('tooltip_logo'),
                'toolTip_18' => Booth::where('booth_number', 'booth_18')->value('tooltip_logo'),
                'toolTip_19' => Booth::where('booth_number', 'booth_19')->value('tooltip_logo'),
                'toolTip_20' => Booth::where('booth_number', 'booth_20')->value('tooltip_logo'),
                'toolTip_21' => Booth::where('booth_number', 'booth_21')->value('tooltip_logo'),
                'toolTip_22' => Booth::where('booth_number', 'booth_22')->value('tooltip_logo'),
                'toolTip_23' => Booth::where('booth_number', 'booth_23')->value('tooltip_logo'),
                'toolTip_24' => Booth::where('booth_number', 'booth_24')->value('tooltip_logo'),
                'toolTip_25' => Booth::where('booth_number', 'booth_25')->value('tooltip_logo'),
                'toolTip_26' => Booth::where('booth_number', 'booth_26')->value('tooltip_logo'),
                'toolTip_27' => Booth::where('booth_number', 'booth_27')->value('tooltip_logo'),
                'toolTip_28' => Booth::where('booth_number', 'booth_28')->value('tooltip_logo'),
                'toolTip_29' => Booth::where('booth_number', 'booth_29')->value('tooltip_logo'),
                'toolTip_30' => Booth::where('booth_number', 'booth_30')->value('tooltip_logo'),
                'toolTip_31' => Booth::where('booth_number', 'booth_31')->value('tooltip_logo'),
                'toolTip_32' => Booth::where('booth_number', 'booth_32')->value('tooltip_logo'),


                // ToolTip Company Name 
                'company_1' => Booth::where('booth_number', 'booth_1')->value('company_name'),
                'company_2' => Booth::where('booth_number', 'booth_2')->value('company_name'),
                'company_3' => Booth::where('booth_number', 'booth_3')->value('company_name'),
                'company_4' => Booth::where('booth_number', 'booth_4')->value('company_name'),
                'company_5' => Booth::where('booth_number', 'booth_5')->value('company_name'),
                'company_6' => Booth::where('booth_number', 'booth_6')->value('company_name'),
                'company_7' => Booth::where('booth_number', 'booth_7')->value('company_name'),
                'company_8' => Booth::where('booth_number', 'booth_8')->value('company_name'),
                'company_9' => Booth::where('booth_number', 'booth_9')->value('company_name'),
                'company_10' => Booth::where('booth_number', 'booth_10')->value('company_name'),
                'company_11' => Booth::where('booth_number', 'booth_11')->value('company_name'),
                'company_12' => Booth::where('booth_number', 'booth_12')->value('company_name'),
                'company_13' => Booth::where('booth_number', 'booth_13')->value('company_name'),
                'company_14' => Booth::where('booth_number', 'booth_14')->value('company_name'),
                'company_15' => Booth::where('booth_number', 'booth_15')->value('company_name'),
                'company_16' => Booth::where('booth_number', 'booth_16')->value('company_name'),
                'company_17' => Booth::where('booth_number', 'booth_17')->value('company_name'),
                'company_18' => Booth::where('booth_number', 'booth_18')->value('company_name'),
                'company_19' => Booth::where('booth_number', 'booth_19')->value('company_name'),
                'company_20' => Booth::where('booth_number', 'booth_20')->value('company_name'),
                'company_21' => Booth::where('booth_number', 'booth_21')->value('company_name'),
                'company_22' => Booth::where('booth_number', 'booth_22')->value('company_name'),
                'company_23' => Booth::where('booth_number', 'booth_23')->value('company_name'),
                'company_24' => Booth::where('booth_number', 'booth_24')->value('company_name'),
                'company_25' => Booth::where('booth_number', 'booth_25')->value('company_name'),
                'company_26' => Booth::where('booth_number', 'booth_26')->value('company_name'),
                'company_27' => Booth::where('booth_number', 'booth_27')->value('company_name'),
                'company_28' => Booth::where('booth_number', 'booth_28')->value('company_name'),
                'company_29' => Booth::where('booth_number', 'booth_29')->value('company_name'),
                'company_30' => Booth::where('booth_number', 'booth_30')->value('company_name'),
                'company_31' => Booth::where('booth_number', 'booth_31')->value('company_name'),
                'company_32' => Booth::where('booth_number', 'booth_32')->value('company_name'),


                // ToolTip Description
                'desc_1' => Booth::where('booth_number', 'booth_1')->value('description'),
                'desc_2' => Booth::where('booth_number', 'booth_2')->value('description'),
                'desc_3' => Booth::where('booth_number', 'booth_3')->value('description'),
                'desc_4' => Booth::where('booth_number', 'booth_4')->value('description'),
                'desc_5' => Booth::where('booth_number', 'booth_5')->value('description'),
                'desc_6' => Booth::where('booth_number', 'booth_6')->value('description'),
                'desc_7' => Booth::where('booth_number', 'booth_7')->value('description'),
                'desc_8' => Booth::where('booth_number', 'booth_8')->value('description'),
                'desc_9' => Booth::where('booth_number', 'booth_9')->value('description'),
                'desc_10' => Booth::where('booth_number', 'booth_10')->value('description'),
                'desc_11' => Booth::where('booth_number', 'booth_11')->value('description'),
                'desc_12' => Booth::where('booth_number', 'booth_12')->value('description'),
                'desc_13' => Booth::where('booth_number', 'booth_13')->value('description'),
                'desc_14' => Booth::where('booth_number', 'booth_14')->value('description'),
                'desc_15' => Booth::where('booth_number', 'booth_15')->value('description'),
                'desc_16' => Booth::where('booth_number', 'booth_16')->value('description'),
                'desc_17' => Booth::where('booth_number', 'booth_17')->value('description'),
                'desc_18' => Booth::where('booth_number', 'booth_18')->value('description'),
                'desc_19' => Booth::where('booth_number', 'booth_19')->value('description'),
                'desc_20' => Booth::where('booth_number', 'booth_20')->value('description'),
                'desc_21' => Booth::where('booth_number', 'booth_21')->value('description'),
                'desc_22' => Booth::where('booth_number', 'booth_22')->value('description'),
                'desc_23' => Booth::where('booth_number', 'booth_23')->value('description'),
                'desc_24' => Booth::where('booth_number', 'booth_24')->value('description'),
                'desc_25' => Booth::where('booth_number', 'booth_25')->value('description'),
                'desc_26' => Booth::where('booth_number', 'booth_26')->value('description'),
                'desc_27' => Booth::where('booth_number', 'booth_27')->value('description'),
                'desc_28' => Booth::where('booth_number', 'booth_28')->value('description'),
                'desc_29' => Booth::where('booth_number', 'booth_29')->value('description'),
                'desc_30' => Booth::where('booth_number', 'booth_30')->value('description'),
                'desc_31' => Booth::where('booth_number', 'booth_31')->value('description'),
                'desc_32' => Booth::where('booth_number', 'booth_32')->value('description')
            ]);
    }
}